### ISSUE TITLE
1.0.4 Thunder 迅雷字母下载失败

### ISSUE THREAD

**Issue by ystyleb** [91270/MeiamSubtitles#29]
2021-12-28 15:47:45.597 Info HttpClient: GET http://subtitle.v.geilijiasu.com/7F/C1/7FC181F1522293AFA8AFAB77DABE5CAB585DAEDC.ass
2021-12-28 15:47:45.682 Error Server: Error processing request
        *** Error Report ***
        Version: 4.6.7.0
        Command line: /share/CACHEDEV1_DATA/.qpkg/EmbyServer/system/EmbyServer.dll -programdata /share/CACHEDEV1_DATA/.qpkg/EmbyServer/programdata -ffdetect /share/CACHEDEV1_DATA/.qpkg/EmbyServer/bin/ffdetect -ffmpeg /share/CACHEDEV1_DATA/.qpkg/EmbyServer/bin/ffmpeg -ffprobe /share/CACHEDEV1_DATA/.qpkg/EmbyServer/bin/ffprobe -defaultdirectory /share/CACHEDEV1_DATA/Public -updatepackage emby-server-qnap_{version}_x86_64.qpkg -noautorunwebapp
        Operating system: Linux version 5.10.60-qnap (root@U16BuildServer173) (x86_64-QNAP-linux-gnu-gcc (toolchain config: [gcc-4.9.2 binutils-2.25 glibc-2.21]) 4.9.2, GNU ld
        Framework: .NET Core 3.1.21
        OS/Process: x64/x64
        Runtime: share/CACHEDEV1_DATA/.qpkg/EmbyServer/system/System.Private.CoreLib.dll
        Processor count: 4
        Data path: /share/CACHEDEV1_DATA/.qpkg/EmbyServer/programdata
        Application path: /share/CACHEDEV1_DATA/.qpkg/EmbyServer/system
        MediaBrowser.Model.Net.HttpException: MediaBrowser.Model.Net.HttpException: NotFound
           at Emby.Server.Implementations.HttpClientManager.CoreHttpClientManager.SendAsyncInternal(HttpRequestOptions options, String httpMethod)
           at Emby.Server.Implementations.HttpClientManager.CoreHttpClientManager.SendAsync(HttpRequestOptions options, String httpMethod)
           at Emby.MeiamSub.Thunder.ThunderProvider.DownloadSubAsync(String info)
           at Emby.MeiamSub.Thunder.ThunderProvider.GetSubtitles(String id, CancellationToken cancellationToken)
           at MediaBrowser.Providers.Subtitles.SubtitleManager.DownloadSubtitles(Video video, String subtitleId, LibraryOptions libraryOptions, CancellationToken cancellationToken)
           at MediaBrowser.Api.Subtitles.SubtitleService.Post(DownloadRemoteSubtitles request)
           at Emby.Server.Implementations.Services.ServiceController.GetTaskResult(Task task)
           at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost appHost, IRequest httpReq, IResponse httpRes, RestPath restPath, String responseContentType, CancellationToken cancellationToken)
           at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IRequest httpReq, ReadOnlyMemory`1 urlString, ReadOnlyMemory`1 localPath, CancellationToken cancellationToken)
        Source: Emby.Server.Implementations
        TargetSite: Void MoveNext()

**Comment by 91270** [comment]
迅雷的下载地址，目前很多是 404 找不到文件

**Comment by TwinsenLiang** [comment]
最近两边都404
