### ISSUE TITLE
群晖 EMBY 下载字幕报错

### ISSUE THREAD

**Issue by carlchina** [91270/MeiamSubtitles#37]
已经找到可用字幕 但是无法现在，点击下载后报错。

<img width="1044" alt="WX20220405-104700@2x" src="https://user-images.githubusercontent.com/5435458/161669550-1ee23577-78b3-46a3-92d0-9a856ca94bae.png">

```
2022-04-05 10:46:40.826 Info HttpClient: POST http://www.shooter.cn/api/subapi.php
2022-04-05 10:46:40.965 Info HttpClient: GET http://sub.xmp.sandai.net:8000/subxl/60EFC067DDCC51625CE668D361F22071D14AC349.json
2022-04-05 10:46:41.822 Error SubtitleManager: Error downloading subtitles from Open Subtitles
	*** Error Report ***
	Version: 4.6.7.0
	Command line: /volume2/@appstore/EmbyServer/system/EmbyServer.dll -programdata /volume2/Emby -ffdetect /var/packages/EmbyServer/target/bin/ffdetect -ffmpeg /var/packages/EmbyServer/target/bin/ffmpeg -ffprobe /var/packages/EmbyServer/target/bin/ffprobe -nolocalportconfig -ignore_vaapi_enabled_flag -pidfile /volume2/Emby/EmbyServer.pid -defaultdirectory /volume1/Public -updatepackage emby-server-synology_{version}_x86_64.spk -noautorunwebapp
	Operating system: Linux version 4.4.59+ (root@build3) (gcc version 4.9.3 20150311 (prerelease) (crosstool-NG 1.20.0) ) #25426 SMP PREEMPT Mon Dec 14 18:48:50 CST 2020
	Framework: .NET Core 3.1.21
	OS/Process: x64/x64
	Runtime: volume2/@appstore/EmbyServer/system/System.Private.CoreLib.dll
	Processor count: 4
	Data path: /volume2/Emby
	Application path: /volume2/@appstore/EmbyServer/system
	MediaBrowser.Model.Net.HttpException: MediaBrowser.Model.Net.HttpException: ServiceUnavailable
	   at Emby.Server.Implementations.HttpClientManager.CoreHttpClientManager.SendAsyncInternal(HttpRequestOptions options, String httpMethod)
	   at Emby.Server.Implementations.HttpClientManager.CoreHttpClientManager.SendAsync(HttpRequestOptions options, String httpMethod)
	   at OpenSubtitles.OpenSubtitleDownloader.SendRequestAsync(ReadOnlyMemory`1 request, CancellationToken cancellationToken)
	   at OpenSubtitles.OpenSubtitleDownloader.Login(CancellationToken cancellationToken)
	   at OpenSubtitles.OpenSubtitleDownloader.Search(SubtitleSearchRequest request, CancellationToken cancellationToken)
	   at MediaBrowser.Providers.Subtitles.SubtitleManager.<>c__DisplayClass17_0.<<SearchSubtitles>b__3>d.MoveNext()
	Source: Emby.Server.Implementations
	TargetSite: Void MoveNext()
	
2022-04-05 10:46:41.837 Info Server: http/1.1 Response 200 to 192.168.31.149. Time: 1424ms. http://192.168.31.28:8096/emby/Items/23707/RemoteSearch/Subtitles/chi?X-Emby-Client=Emby Web&X-Emby-Device-Name=Chrome&X-Emby-Device-Id=a1b06fb2-ed37-4309-a282-7644047443c8&X-Emby-Client-Version=4.6.7.0
2022-04-05 10:46:45.442 Info Server: http/1.1 POST http://192.168.31.28:8096/emby/Items/23707/RemoteSearch/Subtitles/3ed9002fcf6d3d4d0f4a18811e872b5a_eyJVcmwiOiJodHRwOi8vc3VidGl0bGUudi5nZWlsaWppYXN1LmNvbS9ENy84Mi9ENzgyMTU5NTk1QjVFM0I1MTAzNDJBNjMxNDgxNkJBNjJDMDNFMUQ4LmFzcyIsIkZvcm1hdCI6ImFzcyIsIkxhbmd1YWdlIjoiY2hpIiwiVHdvTGV0dGVySVNPTGFuZ3VhZ2VOYW1lIjoiemgtQ04ifQ==?X-Emby-Client=Emby Web&X-Emby-Device-Name=Chrome&X-Emby-Device-Id=a1b06fb2-ed37-4309-a282-7644047443c8&X-Emby-Client-Version=4.6.7.0. UserAgent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.60 Safari/537.36
2022-04-05 10:46:45.473 Info HttpClient: GET http://subtitle.v.geilijiasu.com/D7/82/D782159595B5E3B510342A6314816BA62C03E1D8.ass
2022-04-05 10:46:45.811 Error Server: Error processing request
	*** Error Report ***
	Version: 4.6.7.0
	Command line: /volume2/@appstore/EmbyServer/system/EmbyServer.dll -programdata /volume2/Emby -ffdetect /var/packages/EmbyServer/target/bin/ffdetect -ffmpeg /var/packages/EmbyServer/target/bin/ffmpeg -ffprobe /var/packages/EmbyServer/target/bin/ffprobe -nolocalportconfig -ignore_vaapi_enabled_flag -pidfile /volume2/Emby/EmbyServer.pid -defaultdirectory /volume1/Public -updatepackage emby-server-synology_{version}_x86_64.spk -noautorunwebapp
	Operating system: Linux version 4.4.59+ (root@build3) (gcc version 4.9.3 20150311 (prerelease) (crosstool-NG 1.20.0) ) #25426 SMP PREEMPT Mon Dec 14 18:48:50 CST 2020
	Framework: .NET Core 3.1.21
	OS/Process: x64/x64
	Runtime: volume2/@appstore/EmbyServer/system/System.Private.CoreLib.dll
	Processor count: 4
	Data path: /volume2/Emby
	Application path: /volume2/@appstore/EmbyServer/system
	MediaBrowser.Model.Net.HttpException: MediaBrowser.Model.Net.HttpException: NotFound
	   at Emby.Server.Implementations.HttpClientManager.CoreHttpClientManager.SendAsyncInternal(HttpRequestOptions options, String httpMethod)
	   at Emby.Server.Implementations.HttpClientManager.CoreHttpClientManager.SendAsync(HttpRequestOptions options, String httpMethod)
	   at Emby.MeiamSub.Thunder.ThunderProvider.DownloadSubAsync(String info)
	   at Emby.MeiamSub.Thunder.ThunderProvider.GetSubtitles(String id, CancellationToken cancellationToken)
	   at MediaBrowser.Providers.Subtitles.SubtitleManager.DownloadSubtitles(Video video, String subtitleId, LibraryOptions libraryOptions, CancellationToken cancellationToken)
	   at MediaBrowser.Api.Subtitles.SubtitleService.Post(DownloadRemoteSubtitles request)
	   at Emby.Server.Implementations.Services.ServiceController.GetTaskResult(Task task)
	   at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost appHost, IRequest httpReq, IResponse httpRes, RestPath restPath, String responseContentType, CancellationToken cancellationToken)
	   at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IRequest httpReq, ReadOnlyMemory`1 urlString, ReadOnlyMemory`1 localPath, CancellationToken cancellationToken)
	Source: Emby.Server.Implementations
	TargetSite: Void MoveNext()
	
```

**Comment by 91270** [comment]
这个是网络环境问题，你可以尝试复制里面字幕下载地址，看你的网络环境是否能够打开

**Comment by 91270** [comment]
http://subtitle.v.geilijiasu.com/D7/82/D782159595B5E3B510342A6314816BA62C03E1D8.ass
404 - NOT FOUND  字幕服务器路径失效的问题

**Comment by carlchina** [comment]
明白了 虽然找到了字幕 但是在对方服务器里文件不存在？还是说字幕服务器防盗链？

**Comment by carlchina** [comment]
但是我发现迅雷的字幕，都是下载不下来的。

**Comment by hisune** [comment]
`Meiamsub Shooter`目测都下不了，`Meiamsub Thunder`有小部分下不了

**Comment by 91270** [comment]
射手 ，测试可以的啊。
迅雷 ，确实有一部分下载不了

**Comment by hutao562** [comment]
![image](https://user-images.githubusercontent.com/76097137/166098110-623051ef-4f0d-42b4-b74a-3a8a93d35749.png)
哎，有什么解决办法吗？
