### ISSUE TITLE
unraid安装docker版emby，插件搜不到字幕

### ISSUE THREAD

**Issue by Always67** [91270/MeiamSubtitles#39]
部分日志如下：
2022-04-20 08:07:43.549 Info App: MeiamSub.Shooter Search | SubtitleSearchRequest -> {"Language":"zh-CN","ContentType":"Movie","MediaPath":"/mnt/remotes/10.0.0.233_Plex/电影/IMDb.2017.09.29.Top.250.BluRay.1080p.x265.10bit.MNHD-FRDS/V字仇杀队 (2006).mkv","Name":"V字仇杀队","ProductionYear":2006,"RuntimeTicks":79528620000,"IsPerfectMatch":false,"ProviderIds":{"Imdb":"tt0434409","Tmdb":"752","Tvdb":"528","Official Website":"http://vforvendetta.warnerbros.com/"},"SearchAllProviders":true,"DisabledSubtitleFetchers":[],"SubtitleFetcherOrder":[]}
2022-04-20 08:07:43.550 Error SubtitleManager: Error downloading subtitles from MeiamSub.Shooter
	*** Error Report ***
	Version: 4.7.0.35
	Command line: /system/EmbyServer.dll -programdata /config -ffdetect /bin/ffdetect -ffmpeg /bin/ffmpeg -ffprobe /bin/ffprobe -restartexitcode 3
	Operating system: Linux version 5.10.28-Unraid (root@Develop) (gcc (GCC) 9.3.0, GNU ld version 2.33.1-slack15) #1 SMP Wed Apr 7 08:23:18 PDT 2021
	Framework: .NET 6.0.2
	OS/Process: x64/x64
	Runtime: system/System.Private.CoreLib.dll
	Processor count: 4
	Data path: /config
	Application path: /system
	System.MissingMethodException: System.MissingMethodException: Method not found: 'System.String MediaBrowser.Controller.Subtitles.SubtitleSearchRequest.get_TwoLetterISOLanguageName()'.
	   at Emby.MeiamSub.Shooter.ShooterProvider.SearchSubtitlesAsync(SubtitleSearchRequest request)
	   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
	   at Emby.MeiamSub.Shooter.ShooterProvider.SearchSubtitlesAsync(SubtitleSearchRequest request)
	   at Emby.MeiamSub.Shooter.ShooterProvider.Search(SubtitleSearchRequest request, CancellationToken cancellationToken)
	   at Emby.Providers.Subtitles.SubtitleManager.<>c__DisplayClass17_0.<<SearchSubtitles>b__3>d.MoveNext()
	Source: Emby.MeiamSub.Shooter
	TargetSite: Void MoveNext()

**Comment by 91270** [comment]
EMBY 那个版本

**Comment by Always67** [comment]
4.7.0.35测试版
