### ISSUE TITLE
windows版emby 4.7.0.60下载字幕报错

### ISSUE THREAD

**Issue by ferdinand474** [91270/MeiamSubtitles#45]
手动搜索无法搜到字幕
![image](https://user-images.githubusercontent.com/38850880/170092389-4817ac74-e520-47dd-abd2-bdb5236dd8fc.png)
照理说这样一部热门电影应该是有字幕的，但是无法搜索到，下面的是报错信息
而且不只是这一部无法搜索到，我试了大部分影片，全部都是搜索不到。
> 2022-05-25 00:56:58.928 Info App: MeiamSub.Shooter Search | SubtitleSearchRequest -> {"Language":"zh-CN","ContentType":"Movie","MediaPath":"E:\\电影\\The.Northman.2022.1080p.AMZN.WEBRip.DDP5.1.Atmos.x264-NOGRP\\The.Northman.2022.1080p.AMZN.WEBRip.DDP5.1.Atmos.x264-NOGRP.mkv","Name":"北欧人","ProductionYear":2022,"RuntimeTicks":82378550000,"IsPerfectMatch":false,"ProviderIds":{"Tmdb":"639933","Imdb":"tt11138512"},"SearchAllProviders":true,"DisabledSubtitleFetchers":[],"SubtitleFetcherOrder":[]}
2022-05-25 00:56:58.929 Error SubtitleManager: Error downloading subtitles from MeiamSub.Shooter
*** Error Report ***
Version: 4.7.0.60
Command line: C:\Users\19022\AppData\Roaming\Emby-Server\system\EmbyServer.dll -noautorunwebapp
Operating system: Microsoft Windows 10.0.19044
Framework: .NET 6.0.2
OS/Process: x64/x64
Runtime: C:/Users/19022/AppData/Roaming/Emby-Server/system/System.Private.CoreLib.dll
Processor count: 8
Data path: C:\Users\19022\AppData\Roaming\Emby-Server\programdata
Application path: C:\Users\19022\AppData\Roaming\Emby-Server\system
System.MissingMethodException: System.MissingMethodException: Method not found: 'System.String MediaBrowser.Controller.Subtitles.SubtitleSearchRequest.get_TwoLetterISOLanguageName()'.
at Emby.MeiamSub.Shooter.ShooterProvider.SearchSubtitlesAsync(SubtitleSearchRequest request)
at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
at Emby.MeiamSub.Shooter.ShooterProvider.SearchSubtitlesAsync(SubtitleSearchRequest request)
at Emby.MeiamSub.Shooter.ShooterProvider.Search(SubtitleSearchRequest request, CancellationToken cancellationToken)
at Emby.Providers.Subtitles.SubtitleManager.<>c__DisplayClass17_0.<<SearchSubtitles>b__3>d.MoveNext()
Source: Emby.MeiamSub.Shooter
TargetSite: Void MoveNext()
2022-05-25 00:56:58.929 Info App: MeiamSub.Thunder Search | SubtitleSearchRequest -> {"Language":"zh-CN","ContentType":"Movie","MediaPath":"E:\\电影\\The.Northman.2022.1080p.AMZN.WEBRip.DDP5.1.Atmos.x264-NOGRP\\The.Northman.2022.1080p.AMZN.WEBRip.DDP5.1.Atmos.x264-NOGRP.mkv","Name":"北欧人","ProductionYear":2022,"RuntimeTicks":82378550000,"IsPerfectMatch":false,"ProviderIds":{"Tmdb":"639933","Imdb":"tt11138512"},"SearchAllProviders":true,"DisabledSubtitleFetchers":[],"SubtitleFetcherOrder":[]}
2022-05-25 00:56:58.980 Info Server: http/1.1 POST http://localhost:8096/emby/DisplayPreferences/usersettings?userId=61dac0b37dfb48abaa6062a0ac0ee8ae&client=emby&X-Emby-Client=Emby Web&X-Emby-Device-Name=Microsoft Edge Windows&X-Emby-Device-Id=3c9bf343-103b-424d-8d4c-58281c9095ee&X-Emby-Client-Version=4.7.0.60&reqformat=json. UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.64 Safari/537.36 Edg/101.0.1210.53
2022-05-25 00:56:58.981 Info Server: http/1.1 Response 204 to 127.0.0.1. Time: 1ms. http://localhost:8096/emby/DisplayPreferences/usersettings?userId=61dac0b37dfb48abaa6062a0ac0ee8ae&client=emby&X-Emby-Client=Emby Web&X-Emby-Device-Name=Microsoft Edge Windows&X-Emby-Device-Id=3c9bf343-103b-424d-8d4c-58281c9095ee&X-Emby-Client-Version=4.7.0.60&reqformat=json
2022-05-25 00:56:59.180 Info HttpClient: POST https://api.opensubtitles.org/xml-rpc
2022-05-25 00:56:59.951 Info HttpClient: POST https://api.opensubtitles.org/xml-rpc
2022-05-25 00:57:00.864 Debug Server: http/1.1 Response 200 to ::1. Time: 1936ms. http://localhost:8096/emby/Items/1983/RemoteSearch/Subtitles/zh-CN?MediaSourceId=f353c9f7dc20311a189d51b481401949&X-Emby-Client=Emby Web&X-Emby-Device-Name=Microsoft Edge Windows&X-Emby-Device-Id=3c9bf343-103b-424d-8d4c-58281c9095ee&X-Emby-Client-Version=4.7.0.60
2022-05-25 00:57:04.437 Debug Server: http/1.1 GET http://localhost:8096/emby/Providers/Subtitles/Subtitles/e02a34f56233e3e5e7765144ca8f184f_srt-chi-1957660714-False?X-Emby-Client=Emby Web&X-Emby-Device-Name=Microsoft Edge Windows&X-Emby-Device-Id=3c9bf343-103b-424d-8d4c-58281c9095ee&X-Emby-Client-Version=4.7.0.60. UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.64 Safari/537.36 Edg/101.0.1210.53
2022-05-25 00:57:04.705 Info HttpClient: POST https://api.opensubtitles.org/xml-rpc
2022-05-25 00:57:05.953 Debug Server: http/1.1 Response 200 to ::1. Time: 1516ms. http://localhost:8096/emby/Providers/Subtitles/Subtitles/e02a34f56233e3e5e7765144ca8f184f_srt-chi-1957660714-False?X-Emby-Client=Emby Web&X-Emby-Device-Name=Microsoft Edge Windows&X-Emby-Device-Id=3c9bf343-103b-424d-8d4c-58281c9095ee&X-Emby-Client-Version=4.7.0.60
2022-05-25 00:57:18.721 Debug Server: http/1.1 GET http://localhost:8096/emby/Providers/Subtitles/Subtitles/e02a34f56233e3e5e7765144ca8f184f_srt-chi-1957660708-False?X-Emby-Client=Emby Web&X-Emby-Device-Name=Microsoft Edge Windows&X-Emby-Device-Id=3c9bf343-103b-424d-8d4c-58281c9095ee&X-Emby-Client-Version=4.7.0.60. UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.64 Safari/537.36 Edg/101.0.1210.53
2022-05-25 00:57:18.980 Info HttpClient: POST https://api.opensubtitles.org/xml-rpc
2022-05-25 00:57:19.963 Debug Server: http/1.1 Response 200 to ::1. Time: 1242ms. http://localhost:8096/emby/Providers/Subtitles/Subtitles/e02a34f56233e3e5e7765144ca8f184f_srt-chi-1957660708-False?X-Emby-Client=Emby Web&X-Emby-Device-Name=Microsoft Edge Windows&X-Emby-Device-Id=3c9bf343-103b-424d-8d4c-58281c9095ee&X-Emby-Client-Version=4.7.0.60
2022-05-25 00:58:32.831 Debug Server: http/1.1 GET http://localhost:8096/emby/Users/61dac0b37dfb48abaa6062a0ac0ee8ae?X-Emby-Client=Emby Web&X-Emby-Device-Name=Microsoft Edge Windows&X-Emby-Device-Id=3c9bf343-103b-424d-8d4c-58281c9095ee&X-Emby-Client-Version=4.7.0.60. UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.64 Safari/537.36 Edg/101.0.1210.53
2022-05-25 00:58:32.831 Debug Server: http/1.1 GET http://localhost:8096/emby/System/Configuration?X-Emby-Client=Emby Web&X-Emby-Device-Name=Microsoft Edge Windows&X-Emby-Device-Id=3c9bf343-103b-424d-8d4c-58281c9095ee&X-Emby-Client-Version=4.7.0.60. UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.64 Safari/537.36 Edg/101.0.1210.53
2022-05-25 00:58:32.832 Debug Server: http/1.1 Response 200 to 127.0.0.1. Time: 1ms. http://localhost:8096/emby/System/Configuration?X-Emby-Client=Emby Web&X-Emby-Device-Name=Microsoft Edge Windows&X-Emby-Device-Id=3c9bf343-103b-424d-8d4c-58281c9095ee&X-Emby-Client-Version=4.7.0.60
2022-05-25 00:58:32.834 Debug Server: http/1.1 GET http://localhost:8096/emby/System/Logs/Query?SortBy=SortName&SortOrder=Ascending&Fields=BasicSyncInfo,CanDelete,Container,PrimaryImageAspectRatio,ProductionYear,Status,EndDate,CommunityRating,OfficialRating,CriticRating,Prefix&ImageTypeLimit=1&EnableImageTypes=Primary,Backdrop,Thumb&StartIndex=0&Limit=30&X-Emby-Client=Emby Web&X-Emby-Device-Name=Microsoft Edge Windows&X-Emby-Device-Id=3c9bf343-103b-424d-8d4c-58281c9095ee&X-Emby-Client-Version=4.7.0.60. UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.64 Safari/537.36 Edg/101.0.1210.53
2022-05-25 00:58:32.837 Debug Server: http/1.1 Response 200 to ::1. Time: 7ms. http://localhost:8096/emby/Users/61dac0b37dfb48abaa6062a0ac0ee8ae?X-Emby-Client=Emby Web&X-Emby-Device-Name=Microsoft Edge Windows&X-Emby-Device-Id=3c9bf343-103b-424d-8d4c-58281c9095ee&X-Emby-Client-Version=4.7.0.60
2022-05-25 00:58:32.841 Debug Server: http/1.1 Response 200 to ::1. Time: 7ms. http://localhost:8096/emby/System/Logs/Query?SortBy=SortName&SortOrder=Ascending&Fields=BasicSyncInfo,CanDelete,Container,PrimaryImageAspectRatio,ProductionYear,Status,EndDate,CommunityRating,OfficialRating,CriticRating,Prefix&ImageTypeLimit=1&EnableImageTypes=Primary,Backdrop,Thumb&StartIndex=0&Limit=30&X-Emby-Client=Emby Web&X-Emby-Device-Name=Microsoft Edge Windows&X-Emby-Device-Id=3c9bf343-103b-424d-8d4c-58281c9095ee&X-Emby-Client-Version=4.7.0.60
2022-05-25 00:58:33.677 Debug Server: http/1.1 GET http://localhost:8096/emby/System/Logs/embyserver.txt/Lines?SortBy=SortName&SortOrder=Ascending&Fields=BasicSyncInfo,CanDelete,Container,PrimaryImageAspectRatio,ProductionYear,Status,EndDate,CommunityRating,OfficialRating,CriticRating,Prefix&ImageTypeLimit=1&EnableImageTypes=Primary,Backdrop,Thumb&StartIndex=0&Sanitize=true&Limit=100&X-Emby-Client=Emby Web&X-Emby-Device-Name=Microsoft Edge Windows&X-Emby-Device-Id=3c9bf343-103b-424d-8d4c-58281c9095ee&X-Emby-Client-Version=4.7.0.60. UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.64 Safari/537.36 Edg/101.0.1210.53

**Comment by wisinfun** [comment]
我是群晖，升级到4.7正式版之后搜索不到字幕了

**Comment by CODYI1** [comment]
+1 更新1.07版本好像依旧不行

**Comment by wisinfun** [comment]
> +1 更新1.07版本好像依旧不行

我也是

**Comment by think2011** [comment]
是的，我也是 1.07 版本，无法搜索字幕

**Comment by 91270** [comment]
搜索不到字幕，也不一定是插件问题，可能你视频的版本，就没有字幕

**Comment by CODYI1** [comment]
> 搜索不到字幕，也不一定是插件问题，可能你视频的版本，就没有字幕

之前我也怀疑过，但是在emby还是4.6插件是1.06时可以搜索得到字幕的电影在emby4.7插件1.07后就搜不到了。

**Comment by LuckyPuppy514** [comment]
Emby v4.7.1.0 （v4.7.0.6应该也是）  
简体语言代码变成了：zh-CN  
我fork改好了，麻烦有空看下有没有问题，合并编译下  
我自己试了 v4.7.1.0 没问题了  
我编译好了：  
https://github.com/LuckyPuppy514/MeiamSubtitles/releases/tag/v1.0.7.1  

![image](https://user-images.githubusercontent.com/53246532/171371892-2d21d439-810d-4688-a856-b5ade533a323.png)

**Comment by wisinfun** [comment]
> Emby v4.7.1.0 （v4.7.0.6应该也是） 简体语言代码变成了：zh-CN 我fork改好了，麻烦有空看下有没有问题，合并编译下 我自己试了 v4.7.1.0 没问题了 我编译好了： https://github.com/LuckyPuppy514/MeiamSubtitles/releases/tag/v1.0.7.1
> 
> ![image](https://user-images.githubusercontent.com/53246532/171371892-2d21d439-810d-4688-a856-b5ade533a323.png)

4.7.0测试已正常
