### ISSUE TITLE
無法下載字幕

### ISSUE THREAD

**Issue by Yswag** [91270/MeiamSubtitles#69]
你好，搜尋到字幕點擊下載時會報錯
EMBY版本是BETA 4.8.0.29

```
2023-04-24 16:11:46.798 Error Server: Error processing request
        *** Error Report ***
        Version: 4.8.0.29
        Command line: /opt/emby-server/system/EmbyServer.dll -programdata /var/lib/emby -ffdetect /opt/emby-server/bin/ffdetect -ffmpeg /opt/emby-server/bin/ffmpeg -ffprobe /opt/emby-server/bin/ffprobe -restartexitcode 3 -updatepackage emby-server-deb_{version}_amd64.deb
        Operating system: Linux version 5.15.104-1-pve (build@proxmox) (gcc (Debian 10.2.1-6) 10.2.1 20210110, GNU ld (GNU Binutils for Debian) 2.35.2) #1 SMP PVE 5.15.104-2 (2
        Framework: .NET 6.0.13
        OS/Process: x64/x64
        Runtime: opt/emby-server/system/System.Private.CoreLib.dll
        Processor count: 4
        Data path: /var/lib/emby
        Application path: /opt/emby-server/system
        System.ArgumentNullException: System.ArgumentNullException: Value cannot be null. (Parameter 'options')
           at Emby.Server.Implementations.HttpClientManager.CoreHttpClientManager.ValidateParams(HttpRequestOptions options)
           at Emby.Server.Implementations.HttpClientManager.CoreHttpClientManager.SendAsyncInternal(HttpRequestOptions options, String httpMethod)
           at Emby.Server.Implementations.HttpClientManager.CoreHttpClientManager.SendAsync(HttpRequestOptions options, String httpMethod)
           at Emby.MeiamSub.Thunder.ThunderProvider.DownloadSubAsync(String info)
           at Emby.MeiamSub.Thunder.ThunderProvider.GetSubtitles(String id, CancellationToken cancellationToken)
           at Emby.Providers.Subtitles.SubtitleManager.DownloadSubtitles(BaseItem item, String subtitleId, LibraryOptions libraryOptions, CancellationToken cancellationToken)
           at Emby.Api.Subtitles.SubtitleService.Post(DownloadRemoteSubtitles request)
           at Emby.Server.Implementations.Services.ServiceController.GetTaskResult(Task task)
           at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost httpHost, IServerApplicationHost appHost, IRequest httpReq, IResponse httpRes, RestPath restPath, String responseContentType, CancellationToken cancellationToken)
           at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IRequest httpReq, ReadOnlyMemory`1 urlString, ReadOnlyMemory`1 localPath, CancellationToken cancellationToken)
        Source: Emby.Server.Implementations
        TargetSite: Void ValidateParams(MediaBrowser.Common.Net.HttpRequestOptions)
```

**Comment by 91270** [comment]
最新版本暂未适配

**Comment by lvekee** [comment]
> 最新版本暂未适配

请问有计划适配新版本么？现在适配的最新版本是哪个版本？[4.8.0.21]版本也没有适配好像
